### ISSUE TITLE
Wordwrap issue

### ISSUE THREAD

**Issue by vjacksonr123** [izzy/twitch-chat#11]
If someone send a long message the text doesn't do a word wrap when it reaches the end of the area defined.  

EX:   sd;lghkfsd;lkhsd;flkhsd;flkhsd;flkhsd;flkgs;dflgksd;flgksd;flgks;dflgksdl;fkg;sdlfkg;sdlfgsdfljkhg;seiuhgy;ser8urhg'sierthjs

Does not fit in a area off 300x500.

Screen shot attached of chat box and stream chat to show example. 

![2022-04-21 13_36_06-OBS 27 2 4 (64-bit, windows) - Portable Mode - Profile_ Twitch 2_1 - Scenes_ Twi](https://user-images.githubusercontent.com/16087766/164530452-cc54cf87-7148-47a6-9f31-46299c025812.png)

**Comment by izzy** [comment]
This was fixed in the current release. https://github.com/izzy/twitch-chat/releases/tag/v0.1.2
