### ISSUE TITLE
Emotes aren't displaying

### ISSUE THREAD

**Issue by rondhi** [izzy/twitch-chat#5]
With the latest update, emotes don't display. I've tried with no arguments and with a bunch on.

`chat.html?direction=horizontal&bubbles=true&badges=true&highlights=true&cmdprefix=!&bots=nightbot&fade_duration=120`

**Comment by andi242** [comment]
this should be fixed in PR https://github.com/izzy/twitch-chat/pull/6

If you need to fix this quickly, delete ` + 'rem'` at the end of line 218.
It should be like this: `emote_size = url.searchParams.get("emote_size");`

**Comment by izzy** [comment]
This should be fixed now :)
